import OpenGL.GL as gl
import fbo
import geometry
import ledlayout

# The WS2811 rendering pipeline uses several framebuffers, each representing a
# different stage of the conversion from an image to GPIO waveforms:
#
#   mainfbo (owned by fbmatrix.renderer)
#       The source image produced by fbmplay, fbmserve, or another renderer.
#
#   ledfbo (owned by fbmatrix.renderer)
#       A 2D emitter-color texture generated by ws2811_ledbuffer: one row per
#       physical string and one column per LED. This stage samples mainfbo at
#       each LED's layout position, applies source-mode overrides and the
#       selected per-emitter shader, and leaves colors in linear RGB.
#
#   bitplane (owned by signalgenerator)
#       A compressed, logical view of the final WS2811 waveform. Instead of
#       storing the timed high/low pulse shape for every transmitted bit, it
#       stores only the literal 0 or 1 which that pulse must represent. The
#       texture is 24 x longest-string because each LED receives 24 serialized
#       color bits (8 red, 8 green, and 8 blue). Y selects the LED position in
#       every string and X selects one of its 24 color bits. One texel packs
#       that logical bit for all parallel strings into three GPIO-bank bytes.
#       For example, texel (0, 7) contains the most-significant red bit of LED
#       7 on every string. Each string's 0 or 1 occupies its assigned GPIO bit
#       in the texel's R, G, or B byte. The physical-output gamma curve is
#       applied while these logical color bits are generated.
#
#   output framebuffer (owned by the display backend or the caller)
#       The final 840 x longest-string scanout image. signalgenerator expands
#       each logical bit from the bitplane into the appropriate timed WS2811
#       high/low pulse, producing the waveform consumed by the GPIO-connected
#       strings.

MAX_LEDS_PER_STRING = 2000
MAX_STRINGS = 14
BITS_PER_LED = 24


def flatten_layout(layout):
    return ledlayout.flatten_string_layout(
        ledlayout.require_xyzc_string_layout(
            layout, MAX_LEDS_PER_STRING, MAX_STRINGS))


class _quad(geometry.base):
    vertex_code = """
        uniform mat4 modelview;
        uniform mat4 projection;
        in vec2 position;
        in vec2 texcoor;
        out vec2 v_texcoor;
        void main() {
            gl_Position = projection * modelview * vec4(position, 0, 1);
            v_texcoor = texcoor;
        } """
    attributes = {'position': 2, 'texcoor': 2}
    primitive = gl.GL_QUADS

    def getVertices(self):
        return {
            'position': [(-1, -1), (+1, -1), (+1, +1), (-1, +1)],
            'texcoor': [(0, 0), (1, 0), (1, 1), (0, 1)],
        }


class _bitgenerator(_quad):
    fragment_code = """
        uniform sampler2D tex;
        uniform int string_length;
        out highp vec4 f_color;
        in highp vec2 v_texcoor;

        const int MASK_A = (1 << 2), MASK_B = (1 << 6);
        const int MASK_C = (1 << 7), MASK_D = (1 << 0);
        const int MASK_E = (1 << 4), MASK_LAT = (1 << 1);
        const int MASK_R1 = (1 << 1), MASK_B1 = (1 << 2);
        const int MASK_R2 = (1 << 0), MASK_G1 = (1 << 1);
        const int MASK_G2 = (1 << 4), MASK_B2 = (1 << 3);
        const int MASK_OE = (1 << 0), MASK_CLK = (1 << 5);

        void setBits(out ivec3 p, int D, int LAT, int A, int B2, int E,
                     int B, int C, int R2, int G1, int G2, int CLK, int OE,
                     int R1, int B1) {
            p.r = (D > 0 ? MASK_D : 0) + (LAT > 0 ? MASK_LAT : 0) +
                  (A > 0 ? MASK_A : 0) + (B2 > 0 ? MASK_B2 : 0) +
                  (E > 0 ? MASK_E : 0) + (B > 0 ? MASK_B : 0) +
                  (C > 0 ? MASK_C : 0);
            p.g = (R2 > 0 ? MASK_R2 : 0) + (G1 > 0 ? MASK_G1 : 0) +
                  (G2 > 0 ? MASK_G2 : 0) + (CLK > 0 ? MASK_CLK : 0);
            p.b = (OE > 0 ? MASK_OE : 0) + (R1 > 0 ? MASK_R1 : 0) +
                  (B1 > 0 ? MASK_B1 : 0);
        }

        int getBit(int string_number, int pixel, int bit) {
            highp vec3 color = texelFetch(
                tex, ivec2(pixel, string_number), 0).rgb;
            color = pow(color, vec3(2.2));
            if (bit < 8)
                return (int(color.r * 255.0) >> (7 - bit)) & 1;
            if (bit < 16)
                return (int(color.g * 255.0) >> (15 - bit)) & 1;
            return (int(color.b * 255.0) >> (23 - bit)) & 1;
        }

        void main() {
            int pixel = int(v_texcoor.y * float(string_length));
            int bit = int(v_texcoor.x * 24.0);
            int R1 = 0, G1 = 0, B1 = 0, R2 = 0, G2 = 0, B2 = 0;
            int D = 0, LAT = 0, A = 0, B = 0, C = 0, E = 0, OE = 0;
            int CLK = 0;
            STRING_BITS;
            ivec3 data;
            setBits(data, D, LAT, A, B2, E, B, C, R2, G1, G2, CLK, OE,
                    R1, B1);
            f_color = vec4(vec3(data) / 255.0, 1.0);
        } """

    def __init__(self, strings, string_length):
        names = ['R1', 'G1', 'B1', 'R2', 'G2', 'B2', 'D',
                 'LAT', 'A', 'B', 'C', 'E', 'OE', 'CLK']
        calls = ['%s = getBit(%d, pixel, bit)' % (name, index)
                 for index, name in enumerate(names[:len(strings)])]
        self.fragment_code = self.fragment_code.replace(
            'STRING_BITS;', ';\n            '.join(calls) + ';')
        self.string_length = string_length
        self.tex = 0
        super().__init__()

    def draw(self):
        gl.glActiveTexture(gl.GL_TEXTURE0)
        gl.glBindTexture(gl.GL_TEXTURE_2D, self.tex)
        gl.glUniform1i(gl.glGetUniformLocation(self.program, 'tex'), 0)
        gl.glUniform1i(gl.glGetUniformLocation(self.program, 'string_length'),
                       self.string_length)
        super().draw()


class signalgenerator(_quad):
    fragment_code = """
        uniform sampler2D bitplane;
        uniform int string_length;
        uniform ivec3 active_mask;
        out highp vec4 f_color;
        in highp vec2 v_texcoor;
        void main() {
            int pixel = int(v_texcoor.y * float(string_length));
            highp float position = v_texcoor.x * 24.0;
            int bit = int(position);
            lowp float offset = position - float(bit);
            ivec3 bits = ivec3(
                texelFetch(bitplane, ivec2(bit, pixel), 0).rgb * 255.0 +
                vec3(0.5));
            ivec3 data;
            if (offset < 0.2) data = active_mask;
            else if (offset < 0.46) data = bits;
            else data = ivec3(0);
            f_color = vec4(vec3(data) / 255.0, 1.0);
        } """

    def __init__(self, layout, supersample):
        self.strings = ledlayout.require_xyzc_string_layout(
            layout, MAX_LEDS_PER_STRING, MAX_STRINGS)
        self.lamps = ledlayout.flatten_string_layout(self.strings)
        self.string_length = max((len(string) for string in self.strings),
                                 default=0)
        if self.string_length == 0:
            raise RuntimeError('WS2811 layout must contain at least one LED')

        self.bitplane = fbo.FBO(BITS_PER_LED, self.string_length,
                                mag_filter=gl.GL_NEAREST,
                                min_filter=gl.GL_NEAREST)
        self.bitgenerator = _bitgenerator(self.strings, self.string_length)

        masks = [(2, 2), (1, 2), (2, 4), (1, 1), (1, 16), (0, 8),
                 (0, 1), (0, 2), (0, 4), (0, 64), (0, 128), (0, 16),
                 (2, 1), (1, 32)]
        self.active_mask = [0, 0, 0]
        for channel, mask in masks[:len(self.strings)]:
            self.active_mask[channel] |= mask
        super().__init__()

    def getVertices(self):
        return {
            'position': [(-1, -1), (+1, -1), (+1, +1), (-1, +1)],
            'texcoor': [(0, 1), (1, 1), (1, 0), (0, 0)],
        }

    def render(self):
        with self.bitplane:
            self.bitgenerator.render()
        super().render()

    def draw(self):
        gl.glActiveTexture(gl.GL_TEXTURE0)
        gl.glBindTexture(gl.GL_TEXTURE_2D, self.bitplane.getTexture())
        gl.glUniform1i(gl.glGetUniformLocation(self.program, 'bitplane'), 0)
        gl.glUniform1i(gl.glGetUniformLocation(self.program, 'string_length'),
                       self.string_length)
        gl.glUniform3i(gl.glGetUniformLocation(self.program, 'active_mask'),
                       *self.active_mask)
        super().draw()

    def setTexture(self, tex):
        self.bitgenerator.tex = tex
